spring:
  application:
    name: voca
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        default_batch_fetch_size: 100
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      encoding: utf-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  profiles:
    active: ${PROFILE}

logging.level:
  org:
    hibernate.SQL: debug
