INSERT INTO word (id, word, mean, book_mark) VALUES
(1, "register", "등록하다", true),
(2, "affordable", "적당한", false),
(3, "considerable", "상당한", true),
(4, "accessible", "접근할 수 있는", true),
(5, "significant", "중요한, 상당한", false),
(6, "relevant", "관련 있는", false),
(7, "informative", "유익한", true),
(8, "productive", "생산적인", false),
(9, "extensive", "폭넓은", false),
(10, "helpful", "도움이 되는", false),
(11, "various", "다양한", false),
(12, "regional", "지역의", false),
(13, "operational", "작동하는", false),
(14, "complimentary", "무료의", false),
(15, "introductory", "입문의, 서두의", false),
(16, "supplementary", "보충의", false),
(17, "timely", "시기적절한", false),
(18, "friendly", "친절한", false),
(19, "be confident", "~을 확신하다", false),
(20, "be reliant on", "~에 의존하다", false),
(21, "be impressed with", "~에 감명받다", false),
(22, "be informed about", "~을 통보받다, 잘 알다", false),
(23, "be informed of", "~을 통보받다, 잘 알다", false),
(24, "be responsive to", "~에 대응하다", false),
(25, "one", "하나의", false),
(26, "each", "각각의", false),
(27, "every", "모든", false),
(28, "another", "또 다른", false),
(29, "many", "많은", false),
(30, "few", "거의 없는", false),
(31, "a few", "약간의", false),
(32, "several", "몇몇의", false),
(33, "both", "둘 다", false),
(34, "a number of", "수많은", false),
(35, "much", "많은", false),
(36, "little", "거의 없는", false),
(37, "a little", "약간의", false),
(38, "a great deal of", "다량의", false),
(39, "a great amount of", "다량의", false),
(40, "all", "모든", false),
(41, "most", "대부분의", false),
(42, "other", "다른", false),
(43, "some", "약간의", false),
(44, "plenty of", "다량의", false),
(45, "any", "약간의, 아무", false),
(46, "no", "하나도 없는", false),
(47, "summary", "요약, 개요", false),
(48, "contribution", "기부(금), 기여, 공헌", false),
(49, "reception", "환영회, 연회, 접수처", false),
(50, "requtation", "평판, 명성", false),
(51, "collection", "수집품, 수거", false),
(52, "restriction", "제한, 제약", false),
(53, "estimate", "추정치, 견적서, 추산하다", false),
(54, "preference", "선호, 기호", false),
(55, "suggestion", "제안, 제의", false),
(56, "location", "지점, 위치", false),
(57, "revision", "수정", false),
(58, "division", "부서", false),
(59, "employment", "고용", false),
(60, "equipment", "장비", false),
(61, "membership", "회원 (자격)", false),
(62, "tourism", "관광업", false),
(63, "importance", "중요성", false),
(64, "experience", "경력, 경험", false),
(65, "rental", "임대", false),
(66, "safety", "안전", false),
(67, "supplier", "공급 업체", false),
(68, "author", "작가", false),
(69, "consultant", "상담가", false),
(70, "resident", "거주자, 주민", false),
(71, "job openings", "일자리 공석", false),
(72, "staff assembly", "직원 총회", false),
(73, "customer satisfaction", "고객 만족", false),
(74, "benefits package", "복리 후생 제도", false),
(75, "expiration date", "만기일", false),
(76, "salese representative", "영업 사원", false),
(77, "safety regulations", "안전 규정", false),
(78, "funding", "자금, 자금 제공", false),
(79, "staffing", "직원 채용", false),
(80, "permit", "허가증", false),
(81, "fund", "자금, 자금을 대다", false),
(82, "permission", "허가", false),
(83, "furniture", "가구", false),
(84, "baggage", "수화물", false),
(85, "product", "제품", false),
(86, "merchandise", "상품", false),
(87, "information", "정보", false),
(88, "support", "지원, 지지하다", false),
(89, "experties", "전문성", false),
(90, "panel", "배심원단", false),
(91, "convenience", "편리, 편의", false),
(92, "phase", "단계, 단계적으로 하다", false),
(93, "maintenance", "유지, 보수", false),
(94, "priority", "우선(권)", false),
(95, "certificate", "증서, 자격증", false),
(96, "security", "보안, 안전", false),
(97, "professional", "전문가, 전문적인", false),
(98, "assembly", "조립, 집회", false),
(99, "architect", "건축가", false),
(100, "initiative", "계획, 주도권, 진취성", false),
(101, "associate", "연상하다, 직원, 동료", false),
(102, "organize", "조직하다, 준비하다", false),
(103, "suitable", "적절한, 적합한", false),
(104, "committee", "위원회", false),
(105, "questionnaire", "설문지", false),
(106, "valuable", "소중한, 귀중한", false),
(107, "token", "표시", false),
(108, "envelope", "봉투", false),
(109, "efficiently", "효율적으로", false),
(110, "positive", "긍정적인", false),
(111, "be famous for", "~로 유명하다", false),
(112, "be suitable for", "~에 적합하다", false),
(113, "be adequate for", "~에 적합하다", false),
(114, "be familiar with", "~에 익숙하다", false),
(115, "be agreeable to", "~에 동의하다", false),
(116, "be accessible to", "~에 접근할 수 있다", false),
(117, "be subject to", "~을 받기 쉽다", false),
(118, "be capable of", "~을 할 수 있다", false),
(119, "highly", "매우", false),
(120, "await", "기다리다", false),
(121, "matter", "문제, 일", false),
(122, "retirement", "은퇴, 퇴직", false),
(123, "decision", "결정", false),
(124, "anniversary", "기념일", false),
(125, "improvement", "개선, 향상", false),
(126, "reservation", "예약", false),
(127, "improve", "개선하다", false),
(128, "continue", "지속하다", false),
(129, "department", "부서", false),
(130, "board meeting", "이사회", false),
(131, "regular hours", "정상 영업시간", false),
(132, "demand", "수요, 요구하다", false),
(133, "access", "접근, 이용하다", false),
(134, "ease", "쉬움, 완화하다", false),
(135, "increase", "증가, 증가하다", false),
(136, "purchase", "구매(품), 구매하다", false),
(137, "concern", "걱정, 관심사", false),
(138, "receipt", "영수증, 수령, 받음", false),
(139, "attendant", "안내원, 수행원", false),
(140, "applicant", "지원자", false),
(141, "supervisor", "감독관, 관리자", false),
(142, "provider", "공급자, 제공자", false),
(143, "unit price", "단가", false),
(144, "perspective", "관점", false),
(145, "particular", "특정한, 특별한", false),
(146, "replacement", "교체, 대체품, 후임자", false),
(147, "require", "필요하다", false),
(148, "revise", "수정하다, 개정하다", false),
(149, "employee", "종업원, 고용인", false),
(150, "attend", "참석하다, 출석하다", false),
(151, "success", "성공", false),
(152, "succeed", "성공하다", false),
(153, "must", "~해야하다, ~일 것이다", false),
(154, "recommend", "추천하다", false),
(155, "recommendation", "추천", false),
(156, "advance", "전진, 다가서다, 사전의", false),
(157, "customer", "손님, 고객", false),
(158, "available", "구할 수 있는, 시간이 있는", false),
(159, "become", "~가 되다", false),
(160, "accountant", "회계사", false),
(161, "consider", "고려하다", false),
(162, "competent", "능숙한, 유능한, 적격인", false),
(163, "reasonable", "타당한, 합당한", false),
(164, "responsive", "신속히 대응하는", false),
(165, "responsible", "책임이 있는", false),
(166, "receive", "받다", false),
(167, "transfer", "옮기다", false),
(168, "conduct", "실시하다, 행동", false),
(169, "qualification", "자격", false),
(170, "recently", "최근에", false),
(171, "hire", "고용하다, 빌리다", false),
(172, "supply", "공급, 공급하다", false),
(173, "subscriber", "구독자", false),
(174, "subscribtion", "구독", false),
(175, "train", "교육시키다", false),
(176, "look for", "~를 찾다", false),
(177, "responsible for", "~에 책임이 있는", false),
(178, "manager", "경영자, 매니저", false),
(179, "renovation", "개조", false),
(180, "renovate", "개조하다", false),
(181, "banquet", "연회", false),
(182, "banquet facility", "연회장", false),
(183, "facility", "시설, 기능", false),
(184, "pavement", "인도, 보도", false),
(185, "aim to v", "~를 목표로 하다", false),
(186, "educate", "교육하다", false),
(187, "attach", "첨부하다", false),
(188, "participate", "참가하다", false),
(189, "effective", "효과적인, ~부터", false),
(190, "effectively", "효과적으로", false),
(191, "celebrate", "기념하다", false),
(192, "celebration", "기념 행사, 기념", false),
(193, "foundation", "토대, 재단, 설립", false),
(194, "purse", "지갑", false),
(195, "supervise", "감독하다", false),
(196, "inform", "알리다", false),
(197, "transport", "수송, 수송하다", false),
(198, "response", "대답, 반응", false),
(199, "propose", "제안하다, 청혼하다", false),
(200, "mutual", "상호간의, 공동의", false),
(201, "completion", "완료", false),
(202, "personal", "개인의, 개인적인", false),
(203, "personnel", "인원(직원들), 인사과", false),
(204, "whether", "~인지 아닌지, ~이든 아니든", false),
(205, "expert", "전문가", false),
(206, "earn", "얻다, 벌다", false),
(207, "respond", "반응하다, 응답하다", false),
(208, "undersell", "~보다 싸게 팔다", false),
(209, "outsell", "~보다 많이 [빨리, 비싸게] 팔다", false),
(210, "put together", "(모아서) 만들다; 작성하다; 조립하다", false),
(211, "flash", "깜빡이다", false),
(212, "rebate", "환불해 주다", false),
(213, "pay off", "성과가 나다, (빚을) 전액 갚다", false),
(214, "disagree", "의견을 달리하다, 일치하지 않다", false),
(215, "single out", "선발하다, 발탁하다", false),
(216, "vaccinate", "예방 접종하다", false),
(217, "treat", "치료하다, 처치하다", false),
(218, "illustrate", "삽화를 쓰다", false),
(219, "sign up", "등록하다", false),
(220, "stream", "연속적으로 전송하다", false),
(221, "recite", "낭송하다, 암송하다", false),
(222, "turn around", "호전되다, 호전시키다", false),
(223, "downsize", "줄이다. 구조조정하다", false),
(224, "depict", "묘사하다", false),
(225, "turn to", "~에게 의지하다, ~을 참조하다", false),
(226, "telecommute", "재택 근무하다 (= work from home)", false),
(227, "transform", "변형시키다", false),
(228, "dispatch", "발송하다", false),
(229, "commend", "칭찬하다; 기리다", false),
(230, "compensate", "보상하다", false),
(231, "undercharge", "과소 청구하다, (요금 등을) 덜 받다", false),
(232, "constitute", "구성하다; ~와 다름없다", false),
(233, "allot", "할당하다", false),
(234, "inaugurate", "개시하다, 취임시키다", false),
(235, "incorporate", "통합하다, 포함하다, 편입하다", false),
(236, "embark on[upon]", "(사업 등에) 착수하다, 시작하다", false),
(237, "induce", "유발하다", false),
(238, "cease", "그치다, 그만두다, 중지하다", false),
(239, "refurbish", "재단장하다", false),
(240, "stipulate", "명시하다", false),
(241, "rectify", "바로잡다, 해결하다", false),
(242, "rave", "격찬하다", false),
(243, "empower", "권한을 부여하다, 권력을 위임하다", false),
(244, "intrigue", "흥미를 돋우다", false),
(245, "allure", "꾀다, 유혹하다", false),
(246, "attest", "증명하다, 입증하다", false),
(247, "liquidate", "청산하다, 정리하다, 현금화하다", false),
(248, "aid", "지원, 원조", false),
(249, "disapproval", "반대", false),
(250, "graduation", "졸업", false),
(251, "auction", "경매", false),
(252, "checkup", "점검, 검사", false),
(253, "guidelines", "지침", false),
(254, "behavior", "행위, 행동", false),
(255, "contents", "내용물", false),
(256, "society", "사회, 협회", false),
(257, "invention", "발명(품)", false),
(258, "government", "정부", false),
(259, "principle", "원리, 원칙, 주의", false),
(260, "factor", "요소, 요인", false),
(261, "loss", "손실(물), 손해", false),
(262, "decade", "10년", false),
(263, "profession", "직업", false),
(264, "abuse", "남용", false),
(265, "lawsuit", "소송, 고소", false),
(266, "mission", "임무, 사명", false),
(267, "public holiday", "공휴일", false),
(268, "administrator", "행정관, 사무관", false),
(269, "diploma", "졸업장, 학위증서", false),
(270, "prerequisite", "필수 조건, 전제 조건", false),
(271, "aptitude", "적성, 소질", false),
(272, "oversight", "실수, 부주의, 간과", false),
(273, "distraction", "방해물", false),
(274, "command", "명령, 지휘: (언어의) 구사 능력", false),
(275, "strife", "갈등, 불화", false),
(276, "infringement", "침해", false),
(277, "gross income", "총소득, 총수입", false),
(278, "deviation", "벗어남, 탈선", false),
(279, "increment", "증가, 증대", false),
(280, "replica", "복제품", false),
(281, "proponent", "지지자, 옹호자", false),
(282, "declaration", "선언, 발표", false),
(283, "depiction", "묘사, 서술", false),
(284, "ballot", "투표 용지, 투표권, 비밀 투표", false),
(285, "accordance", "일치, 조화", false),
(286, "ridership", "(대중교통) 이용자 (수); 승차율", false),
(287, "ambiance", "환경, 분위기", false),
(288, "discrepancy", "불일치", false),
(289, "aspiration", "열망, 포부", false),
(290, "labor dispute", "노동쟁의", false),
(291, "prefer", "선호하다", false),
(292, "technique", "기술, 기법", false),
(293, "digit", "숫자", false),
(294, "sector", "부문, 구역", false),
(295, "trade", "무역", false),
(296, "scholar", "학자", false),
(297, "mechanic", "수리공, 정비사", false),
(298, "liquid", "액체", false),
(299, "merit", "장점", false),
(300, "boardroom", "회의실", false),
(301, "passion", "열정", false),
(302, "time-off", "결근, 휴식", false),
(303, "disaster", "재난, 재해", false),
(304, "merchant", "상인", false),
(305, "experiment", "실험, 실험하다", false),
(306, "electronics", "전자 공학, 전자 제품", false),
(307, "iron", "다리미, 철", false),
(308, "range", "범위, 다양성", false),
(309, "statistics", "통계학", false),
(310, "fever", "열", false),
(311, "shareholder", "주주", false),
(312, "transition", "변화, 이행, 추이", false),
(313, "edge", "가장자리, 유리함", false),
(314, "contestant", "출전자, 경쟁자", false),
(315, "inclination", "경향, 성향", false),
(316, "momentum", "탄력, 추진력", false),
(317, "infusion", "주입, 혼합물", false),
(318, "memorial", "기념물, 기념관", false),
(319, "procurement", "획득, 입수, 조달", false),
(320, "concierge", "안내인, 관리인, 수위", false),
(321, "jeopardy", "위험", false),
(322, "collateral", "담보물", false),
(323, "conjunction", "연합, 공동", false),
(324, "flair", "재능, 솜씨", false),
(325, "bookkeeper", "회계 장부 담당자", false),
(326, "persistence", "지속, 고집", false),
(327, "detector", "발견자, 탐지기", false),
(328, "concession", "양보, 인정", false),
(329, "halt", "중단, 멈춤", false),
(330, "reproduction", "재생, 복제(품)", false),
(331, "excavation", "발굴, 발굴지", false),
(332, "citation", "인용(구), 표창(장)", false),
(333, "strike", "파업", false),
(334, "bargain", "싼 물건, 좋은 조건의 거래", false),
(335, "outerwear", "겉옷, 외투", false),
(336, "handbook", "안내서, 참고서", false),
(337, "difference", "차이, 차액", false),
(338, "interviewer", "면접관", false),
(339, "ownership", "소유(권)", false),
(340, "disease", "질병", false),
(341, "remedy", "치료(법)", false),
(342, "healthcare", "건강 관리, 보건 의료", false),
(343, "tutorial", "교육 자료, 개별 지도", false),
(344, "base", "기반, 토대", false),
(345, "kickoff", "시작, 개시", false),
(346, "discovery", "발견", false),
(347, "finalist", "결승 진출자", false),
(348, "firm", "회사", false),
(349, "patron", "고객, 이용자", false),
(350, "earnings", "수익", false),
(351, "obstacle", "장애물", false),
(352, "surcharge", "추가 요금", false),
(353, "dismissal", "해고", false),
(354, "conglomerate", "대기업, (거대) 복합 기업", false),
(355, "logistics", "물류 사업의, 세부 계획", false),
(356, "complication", "합병증, (복잡하게 만드는) 문제", false),
(357, "prevention", "예방", false),
(358, "veterinarian", "수의사", false),
(359, "circumstance", "상황, 환경", false),
(360, "proceeding", "회의록", false),
(361, "breakthrough", "획기적 발전, 돌파구", false),
(362, "inception", "시작, 개시, 발단", false),
(363, "milestone", "획기적 사건", false),
(364, "proliferation", "확산", false),
(365, "compilation", "편집, 편찬(물)", false),
(366, "circulation", "순환, 유통, 판매 부수", false),
(367, "upswing", "호전, 상승", false),
(368, "hypothesis", "가설", false),
(369, "legislation", "법률, 법안", false),
(370, "identical", "똑같은, 동일한", false),
(371, "steep", "가파른, 급격한", false),
(372, "vacant", "공석의, 비어 있는", false),
(373, "useful", "유용한", false),
(374, "respected", "훌륭한, 평판 있는", false),
(375, "lively", "활기찬, 활발한", false),
(376, "vague", "애매한", false),
(377, "harmful", "해로운, 유해한", false),
(378, "curious", "궁금한, 호기심이 많은", false),
(379, "dissatisfied", "불만스러운", false),
(380, "external", "외부의", false),
(381, "wasteful", "낭비의, 헛된", false),
(382, "realistic", "현실적인", false),
(383, "passionate", "열정적인", false),
(384, "lengthy", "장황한, 너무 긴", false),
(385, "sudden", "갑작스러운", false),
(386, "doubtful", "의심스러운, 확신이 없는", false),
(387, "international", "국제적인", false),
(388, "entry-level", "입문의, 초보자용의", false),
(389, "recreational", "오락의, 레크리에이션의", false),
(390, "patient", "환자, 인내하는", false),
(391, "bilateral", "양자의, 쌍방의", false),
(392, "probationary", "견습 기간 중인", false),
(393, "elaborate", "정교한", false),
(394, "eventful", "다사다난한", false),
(395, "intermittent", "간헐적인", false),
(396, "enlightening", "계몽적인", false),
(397, "tedious", "지루한, 싫증나는", false),
(398, "thrifty", "검소한, 절약하는", false),
(399, "coherent", "일관성 있는", false),
(400, "robust", "튼튼한, 강건한, 확고한", false),
(401, "reciprocal", "상호간의, 서로의", false),
(402, "conventional", "전통적인, 관습적인, 형식적인", false),
(403, "argumentative", "논쟁적인, 토론하기를 좋아하는", false),
(404, "tolerant", "관대한, 인내하는", false),
(405, "utmost", "최대한의, 극도의", false),
(406, "harsh", "거친, 가혹한", false),
(407, "reversible", "뒤집을 수 있는", false),
(408, "irreversible", "되돌릴 수 없는", false),
(409, "concentrated", "집중적인, 농축된", false),
(410, "fundamental", "기본적인, 필수의", false),
(411, "incidental", "부수적인, 부수적인 것", false),
(412, "gradual", "점진적인, 단계적인", false),
(413, "proposed", "제안된", false),
(414, "earliest", "(~가 가능한) 가장 빠른 때", false),
(415, "publisher", "출판인, 출판사", false),
(416, "human resource", "인력", false),
(417, "encourage", "권장하다", false),
(418, "take a survey", "설문 조사에 참여하다", false),
(419, "spent", "이미 쓴", false),
(420, "half", "절반", false),
(421, "budget", "예산", false),
(422, "critic", "비평가, 평론가", false),
(423, "thought-provoking", "시사하는 바가 많은", false),
(424, "novel", "소설", false),
(425, "take place", "일어나다, 개최되다", false),
(426, "those who", "~하는 사람들", false),
(427, "training session", "연수", false),
(428, "merger", "합병", false),
(429, "untrue", "사실이 아닌, 허위의", false),
(430, "sales people", "판매원", false),
(431, "introduction", "도입, 소개", false),
(432, "pursue", "추구하다, 계속하다", false),
(433, "career", "직업, 사회생활", false),
(434, "qualifier", "예선 통과자, 예선전", false),
(435, "decline", "감소, 감소하다, 거절하다, 사양하다", false),
(436, "trace", "추적하다, 흔적", false),
(437, "restoration", "복원", false),
(438, "sincerely", "진심으로", false),
(439, "sincere", "진실된, 진정한", false),
(440, "assistance", "지원, 도움", false),
(441, "take less", "더 적게", false),
(442, "fifteen", "15", false),
(443, "complain", "불평하다, 항의하다", false),
(444, "appreciate", "인정하다, 고마워하다", false),
(445, "appreciation", "감탄, 공감, 감사", false),
(446, "finances", "돈, 금전", false),
(447, "complete", "완료하다, 완벽한", false),
(448, "remain", "(~인 상태로) 남아있다", false),
(449, "least", "최소, 최소로", false),
(450, "professionally", "전문적으로", false),
(451, "beginner", "초보자, 초심자", false),
(452, "begin", "시작하다, 시작되다", false),
(453, "significance", "중요성", false),
(454, "charity", "자선단체", false),
(455, "attempt", "시도, 시도하다", false),
(456, "attraction", "매력, 명소", false),
(457, "refundable", "환불가능한", false),
(458, "fully", "완전히, 충분히", false),
(459, "unfortunately", "불행히도, 유갑스럽게도", false),
(460, "currently", "현재, 지금", false),
(461, "thorough", "빈틈없는, 철저한", false),
(462, "throughly", "완전히, 철저히", false),
(463, "ship", "배, 수송하다", false),
(464, "separation", "분리, 헤어짐", false),
(465, "separately", "따로, 별도로", false),
(466, "finally", "마침내", false),
(467, "directly", "직접, 곧바로", false),
(468, "recently", "최근에", false),
(469, "recent", "최근의", false),
(470, "already", "이미", false),
(471, "yet", "아직 (부정문)", false),
(472, "always", "항상", false),
(473, "often", "자주", false),
(474, "once", "(부사) 한 번, (접속사) ~하자마자, ~할 때", false),
(475, "aboud", "대략", false),
(476, "extremely", "극도로", false),
(477, "even", "심지어", false),
(478, "just", "오직", false),
(479, "only", "오직", false),
(480, "simply", "간단히", false),
(481, "almost", "거의", false),
(482, "lecture", "강의, 강의하다", false),
(483, "last", "지속되다", false),
(484, "shortly", "곧", false),
(485, "nearly", "거의", false),
(486, "closely", "긴밀히, 면밀히", false),
(487, "century", "100년, 세기", false),
(488, "monitor", "모니터, 추적 관찰하다", false),
(489, "prove", "입증하다, 증명하다", false),
(490, "previous", "이전의, 바로 앞의", false),
(491, "employer", "고용주", false),
(492, "individual", "개인, 개인의", false),
(493, "strict", "엄격한", false),
(494, "accurate", "정확한, 정밀한", false),
(495, "outstanding", "뛰어난, 미해결된", false),
(496, "temporary", "일시적인, 임시의", false),
(497, "dining", "식사", false),
(498, "enjoyable", "즐거운", false),
(499, "enjoyably", "즐겁게", false),
(500, "leadership", "대표직, 지도력", false),
(501, "eager", "열심인, 열망하는", false),
(502, "eagerly", "간절하게", false),
(503, "consistent", "한결같은, 일관된", false),
(504, "consistently", "일관하여, 지속적으로", false),
(505, "would", "~일 것이다, will의 과거형", false),
(506, "a summary of", "~의 요약본", false),
(507, "a maximum of", "최대의", false),
(508, "a selection of", "다양한", false),
(509, "a collection of", "~의 모음집", false),
(510, "securely", "안전히, 확실히", false),
(511, "secure", "안전한, 확실한, 고정시키다", false),
(512, "casual", "무심한, 건성의, 평상복, 비정규직", false),
(513, "among", "~에 둘러싸인, ~중에", false),
(514, "particularize", "자세히 다루다", false),
(515, "particularity", "독특함, 꼼꼼함", false),
(516, "numerous", "많은", false),
(517, "overtime", "초과 근무(야근), 초과 근무 수당", false),
(518, "process", "과정, 처리하다", false),
(519, "near", "가까운, 가까이 (형용사, 부사, 시간상으로, 거리상으로)", false),
(520, "loan", "대출", false),
(521, "boast", "자랑하다, 자랑", false),
(522, "either", "어느 하나, 각각, ~도", false),
(523, "buyer", "구매자", false),
(524, "first-time", "처음으로 해보는", false),
(525, "rise", "증가, 급여 인상, 올라가다, 일어나다", false),
(526, "steady", "꾸준한, 변함없는, 균형을 잡다, 다시 안정되다", false),
(527, "steadily", "꾸준히, 꾸준하게", false),
(528, "steadiness", "착실함, 끈기", false),
(529, "luggage", "짐", false),
(530, "subject", "주제, 과목, ~될 수 있는", false),
(531, "accountable", "책임이 있는", false),
(532, "transferable", "이동 가능한, 양도 가능한", false),
(533, "charge", "요금, 청구하다", false),
(534, "rug", "깔개, 무릎덮개", false),
(535, "almost", "거의", false),
(536, "material", "천, 재료, 물질적인", false),
(537, "nearly", "거의", false),
(538, "closed", "닫힌, 폐쇄된", false),
(539, "enjoyable", "즐거운, 유쾌한", false),
(540, "excited", "들뜬, 흥분한", false),
(541, "short", "짧은, 짧게", false),
(542, "enormous", "거대한, 엄청난", false),
(543, "elementary", "초급의, 입문의", false),
(544, "valued", "소중한", false),
(545, "wooden", "나무의, 나무로 만든", false),
(546, "modern", "현대의", false),
(547, "different", "다른", false),
(548, "stunning", "굉장히 아름다운, 깜짝 놀랄", false),
(549, "daily", "매일의, 일상적인", false),
(550, "user-friendly", "다루기 쉬운", false),
(551, "foreseeable", "미리 알 수 있는", false),
(552, "latter", "후반의", false),
(553, "imaginary", "상상의, 가상의", false),
(554, "imaginative", "상상력이 풍부한", false),
(555, "further", "더 멀리에(거리, 과거, 미래), 추가의", false),
(556, "time-consuming", "(많은) 시간이 걸리는", false),
(557, "obvious", "명백한", false),
(558, "corporate", "기업의", false),
(559, "dietary", "음식물의, 규정식의, 규정식, 규정량", false),
(560, "neutral", "중립적인", false),
(561, "imminent", "임박한", false),
(562, "mundane", "평범한, 일상적인", false),
(563, "custodial", "보관의, 관리인의", false),
(564, "on-call", "대기 중인", false),
(565, "unbiased", "편견(선입견) 없는", false),
(566, "marginal", "미미한, 중요하지 않은", false),
(567, "definitive", "확정적인, 최고의", false),
(568, "shallow", "얕은, 피상적인", false),
(569, "solitary", "혼자의, 유일한", false),
(570, "exhaustive", "철저한", false),
(571, "sheer", "순전한, 완전한", false),
(572, "clerical", "사무직의", false),
(573, "pending", "임박한, 미결인", false),
(574, "contemporary", "현대의, 동시대의", false),
(575, "transparent", "투명한", false),
(576, "nominal", "명목상의, 이름뿐인", false),
(577, "rugged", "울퉁불퉁한, 강인하게 생긴", false),
(578, "indigenous", "토착의, 고유한", false),
(579, "high-profile", "세간의 이목을 끄는", false),
(580, "succinct", "간결한", false),
(581, "perpetual", "끊임없는, 영원한", false),
(582, "premature", "시기상조의, 너무 이른", false),
(583, "fortunate", "운이 좋은", false),
(584, "intermediate", "중급의", false),
(585, "conclusive", "결정적인, 확실한", false),
(586, "surrounding", "주위의, 주변의", false),
(587, "vivid", "뚜렷한, 선명한", false),
(588, "welcome", "환영하다, 환영받는, 반가운", false),
(589, "unforeseen", "뜻밖의, 예측하지 못한", false),
(590, "undeniable", "부인할 수 없는, 불가피한", false),
(591, "questionable", "의심스러운, 미심쩍은", false),
(592, "numerical", "수의, 숫자상의, 숫자로 나타낸", false),
(593, "commonplace", "아주 흔한, 흔히 있는 일", false),
(594, "elderly", "나이 든", false),
(595, "hearty", "다정한, 원기 왕성한", false),
(596, "secondhand", "중고의, 간접적인", false),
(597, "disturbing", "충격적인, 불안감을 주는, 방해하는", false),
(598, "anxious", "걱정하는, 불안한", false),
(599, "immobile", "움직이지 않는 (못하는)", false),
(600, "live", "살아 있는, 생방송의", false),
(601, "ancient", "고대의", false),
(602, "immense", "거대한, 막대한", false),
(603, "hostile", "적대적인", false),
(604, "commendable", "칭찬할 만한", false),
(605, "resilient", "탄력 있는, 되돌아가는", false),
(606, "scarce", "부족한, 불충분한", false),
(607, "sporadic", "산발적으로 일어나는", false),
(608, "savvy", "지식, 요령있는, 잘 아는", false),
(609, "palpable", "감지할 수 있는, 뚜렷한", false),
(610, "bountiful", "풍부한, 관대한", false),
(611, "unbeatable", "무적의, 타의 추종을 불허하는", false),
(612, "rigid", "엄격한, 견고한", false),
(613, "steadfast", "확고한, 불변의", false),
(614, "candid", "솔직한", false),
(615, "mounting", "증가하는", false),
(616, "neglectful", "부주의한, 태만한", false),
(617, "bewildering", "어리둥절하게[갈피를 못 잡게] 만드는", false),
(618, "complacent", "자기 만족적인, 현실에 안주하는", false),
(619, "attainable", "달성할 수 있는; 획득할 수 있는", false),
(620, "wary", "주의 깊은, 신중한", false),
(621, "subtle", "미묘한, 영리한, 절묘한", false),
(622, "lingering", "오래가는", false),
(623, "edible", "먹을 수 있는", false),
(624, "vast", "방대한, 막대한", false),
(625, "faithful", "충실한, 신의 있는", false),
(626, "former", "예전의, 전자의", false),
(627, "unknown", "알려지지 않은, 무명의", false),
(628, "entire", "전체의", false),
(629, "prompt", "즉각적인, 신속한", false),
(630, "energetic", "힘이 넘치는, 원기 왕성한", false),
(631, "well-suited", "적절한, 잘 어울리는", false),
(632, "industrious", "근면한", false),
(633, "trustworthy", "믿을 수 있는", false),
(634, "flawless", "결점이 없는", false),
(635, "influential", "영향력 있는", false),
(636, "reusable", "재사용할 수 있는", false),
(637, "amusing", "즐거운, 재미있는", false),
(638, "safe", "안전한", false),
(639, "typical", "전형적인, 대표적인", false),
(640, "official", "공식적인, 공인된", false),
(641, "specific", "구체적인, 특정한", false),
(642, "polite", "예의 바른", false),
(643, "respected", "존경 받는, 평판 높은", false),
(644, "factual", "사실에 기반을 둔", false),
(645, "insightful", "통찰력 있는, 영감 있는", false),
(646, "restful", "평안을 주는, 평온한", false),
(647, "tender", "부드러운", false),
(648, "eventual", "궁극적인", false),
(649, "assertive", "적극적인, 확신에 찬", false),
(650, "exaggerated", "과장된, 과대한", false),
(651, "dominant", "지배적인, 우세한", false),
(652, "lavish", "풍성한, 호화로운", false),
(653, "genuine", "진짜의, 진품의", false),
(654, "in-depth", "심층적인, 깊이 있는", false),
(655, "instrumental", "중요한, 악기에 의한", false),
(656, "distinctive", "독특한", false),
(657, "unrivaled", "경쟁자가 없는, 무적의", false),
(658, "excessive", "과도한, 지나친", false),
(659, "dense", "밀집한, 고밀도의", false),
(660, "inevitable", "불가피한, 피할 수 없는", false),
(661, "succeeding", "이어지는, 계속되는", false),
(662, "integral", "필수적인", false),
(663, "prominent", "두드러진, 탁월한", false),
(664, "neatly", "단정하게, 깔끔하게", false),
(665, "generally", "일반적으로", false),
(666, "surely", "확실히, 틀림없이", false),
(667, "fully", "완전히, 충분히", false),
(668, "severely", "심하게", false),
(669, "seriously", "심각하게, 진지하게", false),
(670, "poorly", "저조하게, 형편없이", false),
(671, "somewhat", "다소, 좀", false),
(672, "rightly", "정확하게, 당연히, 마땅하게", false),
(673, "respectfully", "공손하게, 정중하게", false),
(674, "astonishingly", "놀랍게도", false),
(675, "badly", "몹시 심하게, 부당하게", false),
(676, "heavily", "몹시 심하게", false),
(677, "regrettably", "유감스럽게도", false),
(678, "luxuriously", "사치스럽게, 방탕하게", false),
(679, "loudly", "큰 소리로, 소란스럽게", false),
(680, "proudly", "자랑스럽게", false),
(681, "overhead", "머리 위에", false),
(682, "meanwhile", "그동안에, 한편", false),
(683, "vastly", "대단히, 엄청나게", false),
(684, "agreeably", "기분 좋게, 유쾌하게", false),
(685, "ethically", "윤리적으로, 도덕적으로", false),
(686, "unbearably", "참을 수 없게, 견딜 수 없게", false),
(687, "undoubtedly", "틀림없이, 의심할 여지 없이", false),
(688, "cordially", "진심으로", false),
(689, "discreetly", "분별있게, 사려 깊게", false),
(690, "inherently", "본질적으로", false),
(691, "inevitably", "필연적으로", false),
(692, "coincidentally", "우연히, 동시 발생적으로", false),
(693, "boldly", "대담하게", false),
(694, "loosely", "느슨하게", false),
(695, "swiftly", "빨리, 신속히", false),
(696, "in common", "공통으로", false),
(697, "legally", "법률적으로, 합법적으로(↔ illegally 불법적으로)", false),
(698, "technically", "기술적으로, 전문적으로, 엄밀히 말하면", false),
(699, "involuntarily", "모르는 사이에, 본의 아니게", false),
(700, "sparsely", "희박하게, 드문드문하게", false),
(701, "decidedly", "결정적으로, 명백하게", false),
(702, "allegedly", "주장하는 바에 따르면", false),
(703, "namely", "즉, 다시 말하면", false),
(704, "indeed", "사실, 정말", false),
(705, "actually", "실제로, 사실은", false),
(706, "lately", "최근에", false),
(707, "gradually", "점차, 서서히", false),
(708, "minimally", "최소한으로", false),
(709, "correctly", "정확하게, 올바르게", false),
(710, "sharply", "급격하게, 날카롭게", false),
(711, "roughly", "대략, 거의", false),
(712, "randomly", "무작위로, 임의로", false),
(713, "openly", "공개적으로, 공공연히", false),
(714, "hopefully", "바라건대", false),
(715, "meaningfully", "의미 있게, 의미심장하게", false),
(716, "broadly", "광범위하게, 대체로", false),
(717, "carelessly", "부주의하게, 경솔하게", false),
(718, "traditionally", "전통적으로", false),
(719, "surprisingly", "놀랍게도", false),
(720, "voluntarily", "자발적으로", false),
(721, "obviously", "분명히, 명백히", false),
(722, "regularly", "정기적으로, 규칙적으로", false),
(723, "diligently", "부지런히", false),
(724, "collectively", "전체적으로, 총괄하여", false),
(725, "rightfully", "정당하게, 마땅히", false),
(726, "loyally", "성실히, 충성스럽게", false),
(727, "sensibly", "분별있게", false),
(728, "substantially", "실질적으로, 상당히", false),
(729, "significantly", "상당히 의미 있게", false),
(730, "reluctantly", "마지못해", false),
(731, "persuasively", "설득력 있게", false),
(732, "repeatedly", "반복적으로 되풀이하여", false),
(733, "improperly", "부적절하게", false),
(734, "cautiously", "조심스럽게", false),
(735, "convincingly", "납득이 가도록, 설득력 있게", false),
(736, "utterly", "완전히, 전혀", false),
(737, "deliberately", "고의로, 의도적으로", false),
(738, "productively", "생산적으로", false),
(739, "proportionately", "비례하여, 균형에 맞게", false),
(740, "abruptly", "불쑥, 갑자기", false),
(741, "abundantly", "풍부하게, 많이", false),
(742, "functionally", "기능상, 직무상", false),
(743, "variably", "일정하지 않게", false),
(744, "proficiently", "능숙하게", false),
(745, "spontaneously", "자발적으로, 자연스럽게", false),
(746, "safety gear", "안전 장치", false),
(747, "reclaim", "되찾다", false),
(748, "earning", "벌기, 소득, 수입", false),
(749, "property", "재산, 소유물, 부동산", false),
(750, "act", "행동, 행동하다", false),
(751, "briefly", "잠시, 간단히", false),
(752, "also", "또한, 게다가", false),
(753, "downside", "단점", false),
(754, "most", "(형용사) 대부분의,가장 많은, (부사) 가장 많이, 매우, (대명사) 대부분", false),
(755, "business", "사업, 사업체", false),
(756, "value", "가치있게 생각하다, 평가하다", false),
(757, "loan", "대출, 빌려주다, 대여하다", false),
(758, "staff", "직원, 직원으로 일하다, 직원을 제공하다", false),
(759, "would like", "(공손히) 요청하다, 제안하다", false),
(760, "evaluation", "평가", false),
(761, "absence", "결석, 결근, 부재", false),
(762, "exposition", "설명, 전시회", false),
(763, "explain", "설명하다, 해명하다", false),
(764, "determine", "밝히다, 결정하다", false),
(765, "sale", "판매, 매출, 영업", false),
(766, "monthly", "매월, 매월의", false),
(767, "away", "떨어져, 다른데, 자리에 없는", false),
(768, "while", "~하는 동안", false),
(769, "cargo", "화물", false),
(770, "shipping", "선박, 해상 운송", false),
(771, "confused", "혼란스러운", false),
(772, "observe", "준수하다, 관찰하다", false),
(773, "volunteer", "자원 봉사자, 자원하다", false),
(774, "accept", "접수하다, 받다", false),
(775, "assist", "돕다, 도움이 되다", false),
(776, "deliver", "배송하다, (연설 등을) 하다", false),
(777, "predict", "예측하다, 예견하다", false),
(778, "launch", "시작하다, 출시하다, 출시", false),
(779, "assume", "맡다, 추정하다", false),
(780, "emphasize", "강조하다", false),
(781, "finalize", "마무리짓다", false),
(782, "take on", "떠맡다", false),
(783, "undertake", "떠맡다", false),
(784, "takeover", "떠맡다", false),
(785, "preparation", "준비", false),
(786, "presently", "현재", false),
(787, "present", "현재의, 선물, 현재, 지금", false),
(788, "laboratory", "실험실", false),
(789, "temperature", "온도, 기온", false),
(790, "stability", "안정, 안정성", false),
(791, "cosmetics", "화장품", false),
(792, "specialize", "전공하다", false),
(793, "advertising", "광고, 광고업", false),
(794, "theater", "극장, 관객", false),
(795, "meet", "만나다, 충족하다", false),
(796, "manufacture", "제조하다, 제조, 제품", false),
(797, "in a timely manner", "적절한 시기에, 제 시간에", false),
(798, "refer", "언급하다, 참조하다", false),
(799, "refer to", "(자동사) 참조하다, 관련되다", false),
(800, "gift token", "상품권", false),
(801, "gift certificate", "상품권", false),
(802, "gift voucher", "상품권", false),
(803, "probably", "아마", false),
(804, "retail", "소매, 소매하다", false),
(805, "come", "오다, 제공되다, 포함되다", false),
(806, "appear", "~인 것 같다, 나타나다", false),
(807, "probable", "개연성 있는", false),
(808, "glassware", "유리 제품", false),
(809, "sure", "확신하는", false),
(810, "track", "추적하다, 길, 자국", false),
(811, "distinguished", "유명한, 성공한", false),
(812, "announce", "발표하다, 알리다", false),
(813, "competitor", "경쟁자, 참가자", false),
(814, "deal with", "(자동사) ~을 다루다", false),
(815, "address", "~을 다루다", false),
(816, "participate in", "(자동사) ~에 참석하다", false),
(817, "respond to", "(자동사) ~에 응답하다", false),
(818, "talk about", "(자동사) ~에 대해 말하다", false),
(819, "discuss", "상의하다", false),
(820, "rely upon", "(자동사) ~에 의지하다", false),
(821, "specialize in", "(자동사) ~를 전문으로 하다", false),
(822, "lead to", "(자동사) ~로 이어지다", false),
(823, "attend to", "(자동사) ~에 주의하다", false),
(824, "contribute to", "(자동사) ~에 기여하다", false),
(825, "proceed", "(자동사) 진행하다", false),
(826, "appear", "(자동사) 나타나다", false),
(827, "none", "아무도, 아무것도", false),
(828, "anticipate", "예상하다, 예측하다", false),
(829, "come with", "~가 따라오다", false),
(830, "admission", "입장, 입장료, 가입, 이", false),
(831, "money-back guarantee", "환불 보증", false),
(832, "on time", "제시간에, 정각에", false),
(833, "cargo", "화물", false),
(834, "carrier", "운반 차량", false),
(835, "seek", "찾다, 구하다", false),
(836, "cosmetics", "화장품", false),
(837, "attachment", "첨부 파일", false),
(838, "usually", "보통", false),
(839, "frequently", "자주", false),
(840, "ago", "~전에", false),
(841, "then", "그때에", false),
(842, "previously", "이전에", false),
(843, "starting", "~부터", false),
(844, "as of", "~부터", false),
(845, "presently", "현재", false),
(846, "at the moment", "지금", false),
(847, "at that time", "그때", false),
(848, "inspector", "검사관", false),
(849, "examine", "점검하다", false),
(850, "go through", "~을 겪다", false),
(851, "establish", "설립하다", false),
(852, "bill", "청구서, 청구서를 보내다", false),
(853, "award", "수여하다", false),
(854, "entry", "출품작, 입장", false),
(855, "fair", "타당한, 타당하게, 박람회", false),
(856, "alert", "기민한, (위험 등을) 알리다, 경보", false),
(857, "be known for", "~로 유명하다", false),
(858, "be qualified for", "~에 적격이다", false),
(859, "be required for", "~을 위해 요구되다", false),
(860, "be interested in", "~에 관심 있다", false),
(861, "be included in", "~에 포함되다", false),
(862, "be engaged in", "~에 종사하다, 관여하다", false),
(863, "be pleased with", "~로 기뻐하다", false),
(864, "be satisfied with", "~에 만족하다", false),
(865, "be equipped with", "~을 갖추고 있다", false),
(866, "be provided with", "~을 제공받다", false),
(867, "be faced with", "~에 직면하다", false),
(868, "be replaced with", "~으로 교체되다", false),
(869, "be based on", "~에 기초를 두다", false),
(870, "attract", "마음을 끌다, 끌어들이다", false),
(871, "maintain", "유지하다", false),
(872, "resolve", "해결하다, 다짐하다", false),
(873, "cooperate", "협력하다, 협조하다", false),
(874, "resign", "사임하다, 물러나다", false),
(875, "commence", "시작되다, 시작하다", false),
(876, "confirm", "확인하다, 확정하다", false),
(877, "freeze", "얼다", false),
(878, "profitable", "수익성이 있는", false),
(879, "operating cost", "운영비", false),
(880, "expert judge", "전문 심사위원", false),
(881, "revenue", "수익", false),
(882, "desk clerk", "접수 담당자", false),
(883, "banking", "은행업", false),
(884, "at all times", "항상", false),
(885, "strive to", "~하려고 노력하다", false),
(886, "spokesperson", "대변인", false),
(887, "cuisine", "요리, 요리법", false),
(888, "essential", "필수적인", false),
(889, "intend", "의도하다", false),
(890, "tend", "경향이 있다", false),
(891, "afford", "여유가 있다", false),
(892, "strive", "노력하다", false),
(893, "refuse", "거절하다", false),
(894, "reply", "대답, 대답하다", false),
(895, "a plan to부정사", "~할 계획", false),
(896, "a way to부정사", "~할 방법", false),
(897, "a right to부정사", "~할 권리", false),
(898, "an effort to부정사", "~하려는 노력", false),
(899, "a time to부정사", "~할 시간", false),
(900, "an ability to부정사", "~할 능력", false),
(901, "an attempt to부정사", "~하려는 시도", false),
(902, "a chance to부정사", "~할 기회", false),
(903, "an opportunity to부정사", "~할 기회", false),
(904, "honor", "기리다", false),
(905, "be eager to부정사", "~하기를 열망하다", false),
(906, "be able to부정사", "~을 할 수 있다", false),
(907, "be unable to부정사", "~을 할 수 없다", false),
(908, "be sure to부정사", "반드시 ~하다", false),
(909, "be honored to부정사", "~하게 되어 영광이다", false),
(910, "be likely to부정사", "~할 것 같다", false),
(911, "be asked to부정사", "~하도록 요청받다", false),
(912, "be scheduled to부정사", "~할 예정이다", false),
(913, "be supposed to부정사", "~하기로 되어 있다", false),
(914, "be advised to부정사", "~하도록 권고받다", false),
(915, "be please to부정사", "~해서 기쁘다", false),
(916, "encourage", "격려하다, 권장하다", false),
(917, "sales associate", "영업 사원", false),
(918, "stop in at", "~에 들르다", false),
(919, "roadwork", "도로 공사", false),
(920, "keep", "유지하다, 계속하다", false),
(921, "avoid", "피하다", false),
(922, "give up", "포기하다", false),
(923, "give quit", "포기하다", false),
(924, "put off", "연기하다", false),
(925, "mind", "꺼리다", false),
(926, "discontinue", "중단하다", false),
(927, "patron", "고객", false),
(928, "diverse", "다양한", false),
(929, "penalty fee", "벌급, 위약금", false),
(930, "on -ing", "~하자마자", false),
(931, "upon -ing", "~하자마자", false),
(932, "be busy -ing", "~하느라 바쁘다", false),
(933, "be capable of -ing", "~할 수 있다", false),
(934, "have trouble -ing", "~하는 데 어려움이 있다", false),
(935, "prevent A from -ing", "A가 ~하는 것을 막다", false),
(936, "adapt to -ing", "~에 적응하다", false),
(937, "object to -ing", "~에 반대하다", false),
(938, "look forward to -ing", "~을 고대하다", false),
(939, "pay attention to -ing", "~하는 데 유의하다", false),
(940, "be related to -ing", "~와 관련되다", false),
(941, "be opposed to -ing", "~에 반대하다", false),
(942, "be dedicated to -ing", "~에 헌신하다", false),
(943, "be devoted to -ing", "~에 헌신하다", false),
(944, "be committed to -ing", "~에 전념하다", false),
(945, "be accustomed to -ing", "~에 익숙하다", false),
(946, "be used to -ing", "~에 익숙하다", false),
(947, "rising", "오르는, 증가하는", false),
(948, "adopt", "채택하다, 도입하다", false),
(949, "broaden", "넓히다, 확대하다", false),
(950, "arrange", "마련하다, 정리하다", false),
(951, "ensure", "보장하다, 확실하게 하다", false),
(952, "issue", "발행하다", false),
(953, "dispose", "처리하다, 배치하다", false),
(954, "resume", "재개하다", false),
(955, "accommodate", "수용하다, 숙박시키다", false),
(956, "notify", "알리다, 통지하다", false),
(957, "identify", "확인하다, 찾다", false),
(958, "occupy", "차지하다, 사용하다", false),
(959, "familiarize", "익숙하게 하다", false),
(960, "suspend", "중단하다, 유보하다", false),
(961, "potential", "잠재적인, 잠재력", false),
(962, "sensitive", "민감한", false),
(963, "efficiency", "효율, 효율성", false),
(964, "aspiring", "열망하는, 장차 ~가 되려는", false),
(965, "safety protocols", "안전 규약", false),
(966, "comply with", "~을 준수하다", false),
(967, "overall", "전반적인", false),
(968, "head landscaper", "수석 조경사", false),
(969, "be in line with", "~와 일치하다", false),
(970, "farewell gathering", "송별 모임", false),
(971, "apply to", "~에 적용되다", false),
(972, "plant", "식물, 공장, 심다", false),
(973, "according to", "(전치사) ~에 따르면", false),
(974, "rapid", "빠른", false),
(975, "reserve", "예약하다, 보류하다", false),
(976, "stability", "안정, 안정성", false),
(977, "announce", "발표하다, 선언하다", false),
(978, "commence", "시작되다, 시작하다", false),
(979, "concern", "영향을 미치다, 걱정", false),
(980, "acquire", "습득하다, 획득하다", false),
(981, "management", "경영, 경영진, 관리", false),
(982, "accord", "합의, 부여하다, 부합하다", false),
(983, "beside", "(전치사) 옆에, ~에 비해", false),
(984, "besides", "(전치사) ~외에, (부사) 게다가, 또(한)", false),
(985, "however", "아무리 ~해도, 하지만, 그러나", false),
(986, "wore", "입다(wear의 과거형)", false),
(987, "rapidly", "빠르게, 급격히", false),
(988, "approaching summer", "다가오는 여름", false),
(989, "existing equipment", "기존 장비", false),
(990, "leading complaints", "주된 불만 사항들", false),
(991, "promising location", "유망한 지역", false),
(992, "rising prices", "오르는 가격", false),
(993, "desired results", "바라던 결과", false),
(994, "proposed initiative", "제안된 계획안", false),
(995, "required document", "필요 서류", false),
(996, "qualified candidates", "자격을 갖춘 지원자들", false),
(997, "interesting", "흥미로운, 재미있는", false),
(998, "interested", "흥미 있는", false),
(999, "confusing", "혼란스러운", false),
(1000, "disappointed", "실망한", false),
(1001, "embarrassing", "난처한, 당황스러운", false),
(1002, "embarrassed", "쑥스러운, 어색한, 당황스러운", false),
(1003, "exciting", "신난, 흥미진진한", false),
(1004, "excited", "신난, 즐거운", false),
(1005, "amazing", "놀라운", false),
(1006, "amazed", "놀란", false),
(1007, "surprising", "놀라운", false),
(1008, "surprised", "놀란", false),
(1009, "frustrating", "불만스러운, 좌절감을 주는", false),
(1010, "frustrated", "불만스러운, 좌절한", false),
(1011, "tiring", "피곤한, 피곤하게 하는", false),
(1012, "tired", "지친, 피곤한", false),
(1013, "satisfying", "만족스러운, 만족감을 주는", false),
(1014, "spacious", "널찍한", false),
(1015, "fuel efficient", "연료 효율이 높은", false),
(1016, "law firm", "법률 회사", false),
(1017, "local", "지역의, 현지의", false),
(1018, "legal", "법적인", false),
(1019, "formal", "공식적인", false),
(1020, "seasonal", "계절의, 제철의", false),
(1021, "potential", "잠재적인, 잠재력", false),
(1022, "remaining inventory", "남아있는 재고", false),
(1023, "residential", "주택지의, 주거의", false),
(1024, "managerial", "관리의, 경영의", false),
(1025, "affordable", "적당한, 저렴한", false),
(1026, "favorable", "호의적인, 유리한", false),
(1027, "considerable", "상당한, 많은", false),
(1028, "valuable", "소중한, 귀중한", false),
(1029, "probable", "가능성 있는, 유망한", false),
(1030, "multiple", "많은, 다수의", false),
(1031, "import", "수입, 수입품, 수입하다, 불러오다", false),
(1032, "adjacent", "인접한, 가까운", false),
(1033, "adjacent to", "인접한, 가까운", false),
(1034, "flight", "여행, 비행, 항공편, 차다", false),
(1035, "redirect", "다시 보내다, 돌려쓰다", false),
(1036, "energy efficient", "에너지 효율이 좋은", false),
(1037, "manufacture", "제조하다, 제조, 제품", false),
(1038, "approach", "다가가다, 접근법", false),
(1039, "expand", "확대되다, 확대시키다", false),
(1040, "neighboring", "이웃의, 근접한", false),
(1041, "open", "열려있는, 열다, 야외", false),
(1042, "until", "(접속사, 전치사) ~까지", false),
(1043, "electrical", "전기의", false),
(1044, "featrue", "특징, 특징으로 삼다", false),
(1045, "bistro", "작은 식당", false),
(1046, "prepare", "준비하다", false),
(1047, "gourmet bean", "고급 원두", false),
(1048, "anyone", "누구나", false),
(1049, "for", "(목적) ~을 위해, (대상) ~에게, (기간) ~동안, (이유) ~때문에, ~에 대해서", false),
(1050, "right", "(형용사) 올바른, (부사) 바로, (명사) 권리, 오른쪽", false),
(1051, "otherwise", "그렇지 않으면, 그 외에는", false),
(1052, "as if", "마치 ~인 것처럼, 흡사 ~와도 같이", false),
(1053, "although", "~이긴 하지만, 그러나, 하지만", false),
(1054, "therefore", "그러므로, 그러니", false),
(1055, "bowl", "그릇, 통, 공을 굴리다", false),
(1056, "among", "~에 둘러싸인, ~중에서", false),
(1057, "fare", "요금, 승객, 음식", false),
(1058, "diner", "식사하는 사람, 작은 식당", false),
(1059, "official opening", "정식 개업", false),
(1060, "portrait", "초상화", false),
(1061, "preview", "시사회, 시사평, 시사평을 쓰다", false),
(1062, "enthusiast", "열렬한 지지자", false),
(1063, "lever", "레버, 지렛대", false),
(1064, "underneath", "~의 밑에, 속으로 밑면", false),
(1065, "desire", "욕구, 바람, 바라다", false),
(1066, "height", "높이, 키", false),
(1067, "wing", "별관", false),
(1068, "most", "최대, 대부분, 가장, 최고로", false),
(1069, "residence", "주택, 거주지", false),
(1070, "be honored toV", "~하게돼서 기쁘다", false),
(1071, "be pleased toV", "~하게돼서 기쁘다", false),
(1072, "be delighted toV", "~하게돼서 기쁘다", false),
(1073, "considerate", "사려깊은, 배려하는", false),
(1074, "in person", "직접", false),
(1075, "in Ving", "~하는데 있어서", false),
(1076, "on Ving", "~하자마자", false),
(1077, "upon Ving", "~하자마자", false),
(1078, "toward", "~쯤, 무렵", false),
(1079, "domestic", "국내의, 가정의, 가정부", false),
(1080, "cider", "사과주", false),
(1081, "responsibility", "책임, 의무", false),
(1082, "wise", "지혜로운, 현명한", false),
(1083, "enthusiastically", "열정적으로", false),
(1084, "enthusiastic", "열렬한, 열정적인", false),
(1085, "enthusiasm", "열정", false),
(1086, "enthuse", "열변을 토하다, 열광하게 만들다", false),
(1087, "wheel", "바퀴, 핸들, (바퀴 달린 것을) 밀다, 태우고 가다", false),
(1088, "alignment", "가지런함, 지지", false),
(1089, "wheel alignment", "휠 얼라인먼트", false),
(1090, "willing", "기꺼이 하는", false),
(1091, "assort", "분류하다, 어울리다", false),
(1092, "prohibit", "금지하다", false),
(1093, "bother", "신경쓰다, 괴롭히다", false),
(1094, "tailor", "재단사, 조정하다", false),
(1095, "suit", "정장, 어울리다", false),
(1096, "above", "(전치사) ~보다 위에, ~보다 많은, (부사) 위에, ~이상으로", false),
(1097, "far", "멀리, 멀리 있는", false),
(1098, "publicist", "홍보 담당자", false),
(1099, "renowned", "유명한", false),
(1100, "northbound", "북쪽으로 향하는", false),
(1101, "reinforcement", "증강 병력, 강화", false),
(1102, "competitively", "경쟁적으로", false),
(1103, "representative", "대표, 대리인, 대표하는, 전형적인", false),
(1104, "at", "(시각) ~에, (장소) 에서", false),
(1105, "on", "~에 관하여, (시각) ~에, (장소) ~위에, ~에서", false),
(1106, "in", "(시각) ~에, (장소) ~에서", false),
(1107, "from", "~부터", false),
(1108, "since", "~이래로 쭉", false),
(1109, "by", "~까지(완료), ~의 옆에, ~으로, ~을 타고, ~만큼, ~에 의해", false),
(1110, "before", "~전에", false),
(1111, "prior to", "~전에", false),
(1112, "after", "~후에", false),
(1113, "toward", "쯤, 무렵", false),
(1114, "for", "(목적) ~을 위해, (대상) ~에게, (기간) ~동안, (이유) ~때문에, ~에 대해서", false),
(1115, "over", "(장소) ~위에, (기간) ~동안", false),
(1116, "during", "~동안", false),
(1117, "throughout", "~ 곳곳에, (기간) ~내내", false),
(1118, "within 기간", "~이내에", false),
(1119, "at", "(시각) ~에, (장소) 에서", false),
(1120, "in 국가/도시명/공간", "~에서", false),
(1121, "on", "~에 관하여, (시각) ~에, (장소) ~위에, ~에서", false),
(1122, "by", "~까지(완료), ~의 옆에, ~으로, ~을 타고, ~만큼, ~에 의해", false),
(1123, "beside", "~의 옆에", false),
(1124, "next to", "~의 옆에", false),
(1125, "behind", "~의 뒤에", false),
(1126, "near", "(전치사) ~에서 가까이, (형용사) 가까운, (부사) 가까이", false),
(1127, "around", "~의 주위에", false),
(1128, "across", "(전치사) ~에 걸쳐, (부사) 건너서", false),
(1129, "between", "(둘) 사이에", false),
(1130, "among", "(셋 이상) 사이에", false),
(1131, "from", "~부터", false),
(1132, "to", "~로, ~에게", false),
(1133, "inside", "~으로, ~안에", false),
(1134, "through", "~을 통하여", false),
(1135, "by", "~까지(완료), ~의 옆에, ~으로, ~을 타고, ~만큼, ~에 의해", false),
(1136, "with", "~으로, ~하게", false),
(1137, "without", "~없이", false),
(1138, "on", "~에 관하여, (시각) ~에, (장소) ~위에, ~에서", false),
(1139, "over", "(장소) ~위에, (기간) ~동안", false),
(1140, "in", "(시각) ~에, (장소) ~에서", false),
(1141, "except", "~을 제외하고", false),
(1142, "except for", "~을 제외하고", false),
(1143, "because of", "~ 때문에", false),
(1144, "due to", "~ 때문에", false),
(1145, "owing to", "~ 때문에", false),
(1146, "despite", "~에도 불구하고", false),
(1147, "ahead of", "~ 전에", false),
(1148, "instead of", "~ 대신에", false),
(1149, "in addition to", "(전치사) ~에 더하여, ~ 뿐만 아니라", false),
(1150, "regardless of", "~와 상관없이", false),
(1151, "in case of", "~의 경우에", false),
(1152, "in the event of", "~의 경우에", false),
(1153, "in preparation for", "~을 대비하여", false),
(1154, "including", "(전치사) ~을 포함하여", false),
(1155, "beginning", "(전치사) ~부터", false),
(1156, "following", "(전치사) ~ 이후에", false),
(1157, "considering", "(전치사) ~을 고려하면", false),
(1158, "regarding", "(전치사) ~에 관하여", false),
(1159, "concerning", "(전치사) ~에 관하여", false),
(1160, "souvenir", "기념품", false),
(1161, "take place", "개최되다", false),
(1162, "shut off", "멈추다, 중지하다", false),
(1163, "negotiation", "협상", false),
(1164, "massive", "엄청난, 거대한", false),
(1165, "impressive", "인상적인", false),
(1166, "innovative", "혁신적인, 획기적인", false),
(1167, "defective", "결함 있는, 불량인", false),
(1168, "constructive", "건설적인", false),
(1169, "consecutive", "연이은", false),
(1170, "satisfactory", "만족스러운", false),
(1171, "supervisory", "감독의, 관리의", false),
(1172, "convenient", "편리한, 간편한", false),
(1173, "superior", "우수한, 상관의, 상급자", false),
(1174, "sufficient", "충분한", false),
(1175, "new hire", "신입 사원", false),
(1176, "postpone", "연기하다", false),
(1177, "stock", "재고, 주식, 채우다", false),
(1178, "flooding", "홍수", false),
(1179, "downtown", "(부사) 시내에", false),
(1180, "fourth", "네 번째의", false),
(1181, "fall", "떨어지다", false),
(1182, "harvest", "수확", false),
(1183, "in exchange for", "~대신의, 교환으로", false),
(1184, "along with", "(전치사) ~와 함께, ~에 더하여", false),
(1185, "regard", "~을 ~으로 여기다(평가하다), 관심, 존경", false),
(1186, "letter", "편지", false),
(1187, "period", "기간, 시기", false),
(1188, "along", "(전치사) ~을 따라", false),
(1189, "in accordance with", "(전치사) ~에 따라서", false),
(1190, "arrival", "도착, 도착한 사람", false),
(1191, "visit", "방문, 방문하다", false),
(1192, "for free", "무료로", false),
(1193, "until further notice", "추후 공지가 있을 때까지", false),
(1194, "onto", "~로, ~쪽으로", false),
(1195, "benefit dinner", "자선 만찬", false),
(1196, "twofold", "이중적인, 두 배의", false),
(1197, "related to", "(전치사) ~와 관련된", false),
(1198, "indecisive", "우유부단한", false),
(1199, "al least", "(부사) 적어도, 최소한", false),
(1200, "automate", "자동화하다", false),
(1201, "automation", "자동화", false),
(1202, "debit", "인출하다", false),
(1203, "hold", "잡다, 잡기, 정지", false),
(1204, "downtown", "(부사) 시내에", false),
(1205, "fourth", "네 번째의", false),
(1206, "harvest", "수확", false),
(1207, "in exchange for", "~대신의, 교환으로", false),
(1208, "along with", "(전치사) ~와 함께, ~에 더하여", false),
(1209, "regard", "~을 ~으로 여기다(평가하다), 관심, 존경", false),
(1210, "as well", "(부사) 또한, 역시", false),
(1211, "provided that", "(접속사) ~하는 조건으로, ~하는 한", false),
(1212, "sculpture", "조각품, 조각", false),
(1213, "period", "기간, 시기", false),
(1214, "in accordance with", "(전치사) ~에 따라서", false),
(1215, "for free", "(부사) 무료로", false),
(1216, "as", "(전치사) ~처럼, ~로, (부사) ~만큼", false),
(1217, "benefit dinner", "자선 만찬", false),
(1218, "related to", "(전치사) ~와 관련된", false),
(1219, "indecisive", "우유부단한", false),
(1220, "al least", "(부사) 적어도, 최소한", false),
(1221, "other than", "(전치사) ~외에", false),
(1222, "automate", "자동화하다", false),
(1223, "alternatively", "(부사) 그 대신에, 그렇지 않으면", false),
(1224, "debit", "인출하다", false),
(1225, "december", "12월", false),
(1226, "must", "(조동사) ~해야한다, ~임이 틀림없다", false),
(1227, "wing", "날개, 부속 건물, 날아가다, 발송되다", false),
(1228, "additional", "추가적인", false),
(1229, "maximum", "최대(의), 최고(의)", false),
(1230, "selection", "선택, 선발", false),
(1231, "expectation", "예상, 기대", false),
(1232, "expansion", "확장, 확대", false),
(1233, "reference", "추천인, 추천서, 참고, 참조", false),
(1234, "requirement", "(자격) 요건", false),
(1235, "appliance", "가전제품", false),
(1236, "approval", "승인", false),
(1237, "recruiter", "채용 담당자", false),
(1238, "participant", "참가자", false),
(1239, "planning", "계획", false),
(1240, "benefit", "혜택", false),
(1241, "discount", "할인", false),
(1242, "damage", "손해", false),
(1243, "complaint", "불평, 불만", false),
(1244, "agreement", "협약, 계약", false),
(1245, "prepaid", "선불된, 선납된", false),
(1246, "efficient", "효율적인", false),
(1247, "fill in", "채우다", false),
(1248, "be eligible for", "~에 자격이 있다", false),
(1249, "construction", "공사", false),
(1250, "satisfaction", "만족", false),
(1251, "inspection", "검사, 조사", false),
(1252, "assistant", "조수, 보조 요원", false),
(1253, "offer", "제안하다, 제안", false),
(1254, "provide", "제공하다", false),
(1255, "should", "~해야한다", false),
(1256, "educational", "교육의, 교육적인", false),
(1257, "education", "교육", false),
(1258, "transportation", "수송, 수송하다", false),
(1259, "plan", "계획, 계획하다", false),
(1260, "defeat", "패배시키다", false),
(1261, "bury", "매장하다, 묻다", false),
(1262, "devote", "바치다, 헌신하다", false),
(1263, "infect", "감염시키다", false),
(1264, "overestimate", "과대 평가하다", false),
(1265, "confine", "가두다, 한정시키다, 제한하다", false),
(1266, "disperse", "흩어지다", false),
(1267, "characterize", "기술하다, 묘사하다, 특징짓다", false),
(1268, "preclude", "방지하다, 가로막다", false),
(1269, "listing", "표, 목록, 명단", false),
(1270, "journalist", "기자, 언론인", false),
(1271, "pharmacy", "약국", false),
(1272, "outlook", "전망, 견해", false),
(1273, "drawback", "결점; 장애", false),
(1274, "probationer", "견습생, 수습 직원", false),
(1275, "residue", "나머지, 잔류물", false),
(1276, "bond", "유대, 채권", false),
(1277, "forerunner", "전조, 선구자", false),
(1278, "participation", "참가, 참여", false),
(1279, "visitor", "손님, 방문객", false),
(1280, "opposition", "반대(측)", false),
(1281, "allotment", "할당, 분배", false),
(1282, "stagehand", "무대 담당자", false),
(1283, "hurdle", "장애(물), 곤란한 문제", false),
(1284, "fraction", "(전체에 대해) 일부, 작은 부분", false),
(1285, "remnant", "나머지", false),
(1286, "influx", "유입, 밀려듦", false),
(1287, "accessory", "장신구", false),
(1288, "apology", "사과", false),
(1289, "context", "문맥, (사건 등의) 정황, 배경", false),
(1290, "currency", "통화, 화폐", false),
(1291, "tenure", "재임 기간, 보유 기간", false),
(1292, "queue", "줄, 줄을 서서 기다리다", false),
(1293, "disturbance", "방해, 혼란", false),
(1294, "perception", "자각, 인식", false),
(1295, "modest", "겸손한, 적당한", false),
(1296, "active", "활동적인, 적극적인", false),
(1297, "fluent", "유창한", false),
(1298, "unclaimed", "주인이 나서지 않는, 청구하는 사람이 없는", false),
(1299, "philanthropic", "박애(주의)의, 인정 많은", false),
(1300, "noteworthy", "주목할 만한", false),
(1301, "firsthand", "직접의", false),
(1302, "publication", "출판, 발행, 출판물", false),
(1303, "equip", "장비를 갖추다, 준비를 갖춰 주다", false),
(1304, "quite", "매우, 상당히", false),
(1305, "perfume", "향수, 뿌리다", false),
(1306, "public hearing", "공청, 공청회", false),
(1307, "approximately", "거의, 대략", false),
(1308, "around", "대략", false),
(1309, "host", "주인, 주최하다", false),
(1310, "informal", "허물없는, 비공식의", false),
(1311, "serve", "제공하다, 서브", false),
(1312, "invoice", "청구서, 청구서를 보내다", false),
(1313, "attire", "의복, 복장", false),
(1314, "particularly", "특히, 특별히", false),
(1315, "opportunity", "기회", false),
(1316, "favorite", "마음에 드는, 매우 좋아하는", false),
(1317, "gifted", "재능이 있는", false),
(1318, "profound", "깊은, 심오한", false),
(1319, "confirmative", "확증적인", false),
(1320, "susceptible", "민감한, 예민한", false),
(1321, "plentiful", "풍부한, 충분한", false),
(1322, "several", "몇몇의, 각각의", false),
(1323, "restless", "가만히 못 있는, 제대로 쉬지 못하는", false),
(1324, "educated", "교육 받은", false),
(1325, "adaptable", "적응할 수 있는", false),
(1326, "well-prepared", "잘 준비된", false),
(1327, "arbitrary", "임의의, 독단적인", false),
(1328, "leisurely", "느긋한, 여유 있는", false),
(1329, "lax", "느슨한, 해이한", false),
(1330, "absolute", "완전한, 확실한", false),
(1331, "unlikely", "~할 것 같지 않은, 있을 법하지 않은", false),
(1332, "orderly", "정돈된, 질서 있는", false),
(1333, "equal", "동일한, 동등한", false),
(1334, "frequent", "잦은, 빈번한", false),
(1335, "complex", "복잡한, 복합 건물", false),
(1336, "dependent", "의존하는, 의존적인", false),
(1337, "exotic", "이국적인", false),
(1338, "greatly", "대단히, 크게", false),
(1339, "conversely", "반대로", false),
(1340, "fortunately", "다행히도, 운 좋게도(↔ unfortunately 유감스럽게도)", false),
(1341, "readily", "즉시, 손쉽게", false),
(1342, "presumably", "아마, 추측컨대", false),
(1343, "intentionally", "고의로, 의도적으로", false),
(1344, "hastily", "급히, 서둘러서", false),
(1345, "effectively", "효과적으로", false),
(1346, "externally", "외부적으로, 외면적으로", false),
(1347, "artificially", "인위적으로, 인공적으로", false),
(1348, "indefinitely", "무기한으로", false),
(1349, "concisely", "간결하게", false),
(1350, "assertively", "단호히, 단정적으로", false),
(1351, "ever", "(부사) 언제든, 지금껏, 항상", false),
(1352, "a series of", "일련의", false),
(1353, "promote", "촉진하다, 홍보하다, 승진시키다", false),
(1354, "anticipate", "예상하다, 예측하다", false),
(1355, "operate", "(자동사, 타동사) 운영하다, 가동하다", false),
(1356, "direct", "보내다, 안내하다, 직접적인", false),
(1357, "toward", "(전치사) ~쪽으로, ~를 향하여", false),
(1358, "frequently", "자주, 흔히", false),
(1359, "properly", "제대로, 적절히", false),
(1360, "undergo", "(특히 안 좋은 일들을) 겪다, 받다", false),
(1361, "vice president", "부통령, 부대표", false),
(1362, "consult", "상담하다, ~을 참고하다", false),
(1363, "rely on", "(자동사) ~에 의지하다", false),
(1364, "postal supplies", "우편용품", false),
(1365, "upcoming", "다가오는", false),
(1366, "beginning", "~부터", false),
(1367, "defective", "결함 있는", false),
(1368, "be exchanged for", "~으로 교환되다", false),
(1369, "be concerned about", "~에 대해 걱정하다", false),
(1370, "acquire", "얻다, 인수하다", false),
(1371, "in preparation for", "~을 대비하여", false),
(1372, "be ready to부정사", "~할 준비가 되다", false),
(1373, "be willing to부정사", "기꺼이 ~하다", false),
(1374, "be invited to부정사", "~하도록 초대되다/요청받다", false),
(1375, "be required to부정사", "~하는 것이 필수이다", false),
(1376, "by -ing", "(전치사) ~함으로써", false),
(1377, "have difficulty -ing", "~하는 데 어려움이 있다", false),
(1378, "contribute to -ing", "~에 공헌하다", false),
(1379, "lower", "낮추다, (형용사) 아래 쪽의", false),
(1380, "dispose of", "처리하다, 버리다", false),
(1381, "specify", "명시하다, 구체화하다", false),
(1382, "market", "시장, 내놓다, 광고하다", false),
(1383, "worn", "입다(wear의 과거분사)", false),
(1384, "alert", "기민한, (위험 등을) 알리다, 경보", false),
(1385, "growing business", "성장하는 사업", false),
(1386, "personal", "개인적인", false),
(1387, "experienced staff", "경험이 풍부한 직원", false),
(1388, "confused", "혼란스러운", false),
(1389, "disappointing", "실망스러운", false),
(1390, "satisfied", "만족하는, 납득하는", false),
(1391, "boarding pass", "탑승권", false),
(1392, "ingredient", "재료, 구성 요소", false),
(1393, "competent", "능숙한, 유능한, 적격인", false),
(1394, "keep", "유지하다, 지키다, 계속하다", false),
(1395, "anyone", "누구, 아무, 누구나", false),
(1396, "dinner", "식사, 정식, 만찬", false),
(1397, "constant", "끊임없는, 변함없는, 정수", false),
(1398, "exciting", "흥미진진한", false),
(1399, "excited", "신난, 즐거운", false),
(1400, "excite", "흥분시키다", false),
(1401, "by Ving", "(수단) ~함으로써", false),
(1402, "throughout", "(시간) ~내내, (공간) ~전체에", false),
(1403, "passenger", "승객", false),
(1404, "emission", "배출, 배출물, 배기가스", false),
(1405, "as of", "~부터", false),
(1406, "until", "~까지(지속)", false),
(1407, "in front of", "~의 앞에", false),
(1408, "throughout", "~ 곳곳에, (기간) ~내내", false),
(1409, "into", "~으로, ~안에", false),
(1410, "about", "~에 관하여", false),
(1411, "in spite of", "~에도 불구하고", false),
(1412, "across from", "~의 맞은편에", false),
(1413, "starting", "(전치사) ~부터", false),
(1414, "double", "두배의, 두 배, 두 배가 되다", false),
(1415, "collaborative", "협력하는, 공동의", false),
(1416, "former", "예전의, 과거의", false),
(1417, "as well", "(부사) 또한, 역시", false),
(1418, "provided that", "(접속사) ~하는 조건으로, ~하는 한", false),
(1419, "in order that", "(접속사) ~하기 위해서", false),
(1420, "rate", "속도, 비율, 금액, 평가하다", false),
(1421, "sculpture", "조각품, 조각", false),
(1422, "as", "(전치사) ~처럼, ~로, (부사) ~만큼", false),
(1423, "other than", "(전치사) ~외에", false),
(1424, "alternatively", "(부사) 그 대신에, 그렇지 않으면", false),
(1425, "fall", "떨어지다", false),
(1426, "in order that", "(접속사) ~하기 위해서", false),
(1427, "rate", "속도, 비율, 평가하다", false),
(1428, "letter", "편지", false),
(1429, "along", "(전치사) ~을 따라", false),
(1430, "arrival", "도착, 도착한 사람", false),
(1431, "visit", "방문, 방문하다", false),
(1432, "until further notice", "추후 공지가 있을 때까지", false),
(1433, "onto", "~로, ~쪽으로", false),
(1434, "twofold", "이중적인, 두 배의", false),
(1435, "automation", "자동화", false),
(1436, "hold", "잡다, 잡기, 정지", false),
(1437, "although", "(접속사) ~이긴 하지만, 그러나, 하지만", false),
(1438, "nearby", "(형용사) 인근의, (부사) 인근에", false),
(1439, "pass through", "~을 지나가다", false),
(1440, "reception", "접수처, 환영회, 연회, 환영", false);

